const autogen = require('swagger-autogen')();

const outputFile = './src/doc/doc.json';
const endpointFiles = ['./src/routes/index'];

const doc = {
    info: {
        version: "1.0.0",
        title: "Ecommerce API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Users",
            "description": "Endpoints"
        },
        {
            "name": "Products",
            "description": "Endpoints"
        },
        {
            "name": "Images",
            "description": "Endpoints"
        },
        {
            "name": "Auth",
            "description": "Endpoints"
        },
        {
            "name": "Carts",
            "description": "Endpoints"
        },
        {
            "name": "Messages",
            "description": "Endpoints"
        },
        {
            "name": "Orders",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    definitions: {
        User: {
            createdAt: "2000-12-27 14:00:55",
            modifiedAt: "2000-12-27 14:00:55",
            data: {
                username: "aaaaa@gmail.com",
                password: "Password1234",
                repeatedPassword: "RepeeatedPassword1234",
                name: "James",
                surname: "Bond",
                age: "YYYY-MM-DD",
                avatar: "https://www.pinclipart.com/picdir/middle/169-1692839_default-avatar-transparent-clipart.png",
                phoneNumber: "555-555-5555",
                isAdmin:"true/false",
                addresses: [{
                    alias: "Home",
                    street1: {
                        name: "Third Av.",
                         number: "3950"
                            },
                    street2: "Second Av.",
                    street3: "First Av.",
                    zipcode: "AF5544",
                    floor: "1" ,
                    department: "2",
                    city: "Las Vegas",
                    extra_info: "Green door next to the cinema",
                }]                

            }
        },
        Product: {
            createdAt: "2000-12-27 14:00:55",
            modifiedAt: "2000-12-27 14:00:55",
            title: "Big Mc",
            description: "The best of the hamburguers, made with the purest love...",
            price: 9.99,
            stock: 5,
            category: "Burguers",
            images: [{
                url: "https://www.pinclipart.com/picdir/middle/169-1692839_default-avatar-transparent-clipart.png",
                photo_id: "61dd6bdda098374cf6d70a96",
            }]
        },
        Order: {
            
        }
    }
}

autogen(outputFile, endpointFiles, doc).then(() => {
    require('../index')
})